Add starter pack version of readthedocs.yaml

diff --git a/.readthedocs.yaml b/.readthedocs.yaml
--- a/.readthedocs.yaml
+++ b/.readthedocs.yaml
@@ -12,14 +12,21 @@ build:
     python: "3.11"
   jobs:
     post_checkout:
-      - python3 .sphinx/build_requirements.py
-  apt_packages:
-    - distro-info
+    - git fetch --unshallow || true
+    # Cancel building pull requests when there aren't changed in the docs directory.
+    # If there are no changes (git diff exits with 0) we force the command to return with 183.
+    # This is a special exit code on Read the Docs that will cancel the build immediately.
+    # https://docs.readthedocs.io/en/stable/build-customization.html#cancel-build-based-on-a-condition
+    - |
+      if [ "$READTHEDOCS_VERSION_TYPE" = "external" ] && git diff --quiet origin/main -- 'docs/' '.readthedocs.yaml';
+      then
+        exit 183;
+      fi
 
-# Build documentation in the docs/ directory with Sphinx
+# Build documentation with Sphinx
 sphinx:
   builder: dirhtml
-  configuration: conf.py
+  configuration: docs/conf.py
   fail_on_warning: false
 
 # If using Sphinx, optionally build your docs in additional formats such as PDF
@@ -29,4 +36,4 @@ formats:
 # Optionally declare the Python requirements required to build your docs
 python:
    install:
-   - requirements: .sphinx/requirements.txt
+   - requirements: docs/requirements.txt
